baseURL = 'http://example.org/'
languageCode = 'id'
title = 'Nasyid Nusantara'
theme = 'ananke'
resourceDir = "../reseources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Pagination = 3
googleAnalytics = ""
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "black"
  author = "Miminfo"
  favicon = "img/favicon_nasyid.png"
  site_logo = "img/logo_nasyid.png"
  description = "The official nasheed website you'll ever need. Off course."
  background_color_class = "bg-black"

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/nasyid.nusantarapusat"

